#!groovy
// useful links
// https://dzone.com/articles/build-your-pipeline-in-jenkins-20-as-code-with-ios
// https://gist.github.com/jonico/e205b16cf07451b2f475543cf1541e70

WORK_NODE = 'nil'
WORK_SPACE = "/home/jenkins/ch-stage/workspace/ch-server"
DEVELOP_BRANCH = 'develop'
MASTER_BRANCH = 'master'

stage("Select a target node") {
  node('master') {
    echo "Start prepare..."
    switch(BRANCH_NAME) {
    case DEVELOP_BRANCH:
      WORK_NODE = 'chstage-node'
      break
    case MASTER_BRANCH:
      WORK_NODE = 'chprod-node'
      break
    default:
      WORK_NODE = 'chprod-node'
      break
    }
    echo "end prepare the Node is ${WORK_NODE}..."
  }
}

node(WORK_NODE) {
  ws(WORK_SPACE) {
    switch(BRANCH_NAME) {
    case DEVELOP_BRANCH:
      setenv_develop()
      checkout()
      build()
      unit_test()
      deploy()
      break
    case MASTER_BRANCH:
      setenv_production()
      checkout()
      build()
      try {
        deploy()
      } catch(err) {
        rollback()
        slackSend(color: 'danger', message: "New PR FAILED :scream:")
        println(err.getMessage());
      throw err
      }
      break
    default: // PR
      setenv_develop()
      checkout()
      check_codestyle()
      build()
      unit_test()
      slackSend(color: 'good', message: "PR looks good :tada:" )
      break
    }
  }
}

//===============================================================================================================
//===============================================================================================================
//===============================================================================================================

def unit_test() {
  stage("Unit-test"){
    try {
      echo "Start unit-test: '${VAPOR} test ${TEST_PARAM}"
      ansiColor('xterm') {
      sh "$VAPOR test $TEST_PARAM"
    }
      slackSend( color: 'good', message: "Unit-test SUCCESS :smiley:" )
    }catch(err) {
      slackSend(color: 'danger', message: "Unit-test FAILED :scream:")
      println(err.getMessage());
      throw err
    }
  }
}

def setenv_develop() {
  stage("Set environment for develop"){
    //Local paths
    WORK_DIR = "${env.WORKSPACE}"
    SCRIPTS_DIR = "${WORK_DIR}/Devops"

    //MySQL config
    MYSQL_CONFIG = "/home/jenkins/ch-stage/scripts/mysql.json"
    SERVER_CONFIG_DIR = "${WORK_DIR}/Config/development/"

    //Build config
    VAPOR = "/usr/local/bin/vapor"
    BUILD_PARAM = "--verbose"
    TEST_PARAM="--verbose"

    //Deploy config
    env.CH_BUILD = "${env.WORKSPACE}"  // export to scripts
    env.CH_WEBROOT = "/var/www/stage" // export to scripts
    DEPLOY_SCRIPT  = "/usr/bin/sudo -E ${SCRIPTS_DIR}/deploy-build.sh"
    ROLLBACK_SCRIPT = "/usr/bin/sudo -E ${SCRIPTS_DIR}/rollback.sh"

    //For rollback config
    env.DEPLOY_STATUS = "SUCCESS"
    echo "========================"
    sh 'printenv'
    echo "========================"
  }
}

def setenv_production() {
  stage("Set environment for production"){
    //Local paths
    WORK_DIR = "${env.WORKSPACE}"
    SCRIPTS_DIR = "${WORK_DIR}/Devops"

    //MySQL config
    MYSQL_CONFIG = "/home/jenkins/ch-stage/scripts/mysql.json"
    SERVER_CONFIG_DIR = "${WORK_DIR}/Config/production/"

    //Build config
    VAPOR = "/usr/local/bin/vapor"
    BUILD_PARAM = "--verbose --release"

    //Deploy config
    env.CH_BUILD = "${env.WORKSPACE}"  // export to scripts
    env.CH_WEBROOT = "/var/www/stage" // export to scripts
    DEPLOY_SCRIPT  = "/usr/bin/sudo -E ${SCRIPTS_DIR}/deploy-build.sh"
    ROLLBACK_SCRIPT = "/usr/bin/sudo -E ${SCRIPTS_DIR}/rollback.sh"

    //For rollback config
    env.DEPLOY_STATUS = "SUCCESS"
    echo "========================"
    sh 'printenv'
    echo "========================"
  }
}


def check_codestyle() {
  stage("check codestyle"){
    slackSend( color: 'yellow', message: "Checking codestyle under construction :construction:")
  }
}

def checkout(){
  stage("Checkout") {
    try{
      echo "Start checkout on node: ${WORK_NODE}"
      checkout scm
      def COMMIT_MESSAGE = commitMessage()

      slackSend(
        color: 'good',
        message: "Start pipeline for '${env.BRANCH_NAME}' on node '${env.NODE_NAME}' commit message: '${COMMIT_MESSAGE}' Job description: ${env.JOB_NAME} ${env.BUILD_NUMBER} ${env.BUILD_URL}"
      )
    }catch(err) {
      slackSend(color: 'danger', message: "Chekout FAILED :scream:" )
      println(err.getMessage());
      throw err
    }
  }
}

def build() {
  stage("Build"){
    try{
      echo "Copy ${MYSQL_CONFIG} to ${SERVER_CONFIG_DIR}"
      sh "cp ${MYSQL_CONFIG} ${SERVER_CONFIG_DIR}"
      echo "Start build: '${VAPOR} build ${BUILD_PARAM}"
      ansiColor('xterm') {
        sh "$VAPOR build $BUILD_PARAM"
      }
      slackSend( color: 'good', message: "Build SUCCESS :smiley:" )
    }catch(err) {
      slackSend(color: 'danger', message: "Build FAILED :scream:")
      println(err.getMessage());
      throw err
    }
  }
}

def deploy() {
  stage("Deploy"){
    try{
      echo "Start deploy by script ${DEPLOY_SCRIPT}"
      sh "$DEPLOY_SCRIPT"
      currentBuild.result = 'SUCCESS'
      slackSend(color: 'good', message: "Deploy on production on development SUCCESS :smiley: :rocket:")
    } catch(err) {
      currentBuild.result = 'FAILURE'
      slackSend(color: 'danger', message: "Deploy FAILED :scream:" )
      println(err.getMessage());
      throw err
    }
  }
}


def rollback() {
  stage("ROLLBACK"){
    try{
      echo "Start rollback by ${ROLLBACK_SCRIPT}"
      sh "$ROLLBACK_SCRIPT"
      currentBuild.result = 'FAILURE'
      slackSend(color: 'danger', message: "Deploy failed but Rollback is SUCCESS :grimacing:")
    } catch(err) {
      slackSend( color: 'danger', message: "Deploy FAILED and Rollback is FAILED :scream:")
      println(err.getMessage());
      throw err
    }
  }
}


def commitMessage() {
  sh 'git log --format=%B -n 1 HEAD > commitMessage'
  def commitMessage = readFile('commitMessage')
  sh 'rm commitMessage'
  commitMessage
}


